[phases.setup]
nixPkgs = ['python312']
aptPkgs = ['python3-pip', 'python3-dev', 'build-essential']

[phases.install]
cmds = [
    'apt-get update',
    'apt-get install -y python3-pip',
    'cd medical_booking && pip3 install -r requirements.txt --no-cache-dir'
]

[start]
cmd = 'cd medical_booking && python3 manage.py migrate && python3 manage.py collectstatic --noinput && gunicorn medical_booking.wsgi --bind 0.0.0.0:$PORT'

[env]
PYTHONUNBUFFERED = "1"
PORT = "8000"
