[phases.setup]
nixPkgs = ['python312', 'gcc']
aptPkgs = ['python3-pip']

[phases.install]
cmds = [
    'apt-get update',
    'apt-get install -y python3-pip',
    'pip3 install --no-cache-dir -r medical_booking/requirements.txt'
]

[start]
cmd = 'cd medical_booking && python3 manage.py migrate && python3 manage.py collectstatic --noinput && gunicorn medical_booking.wsgi'

[env]
PYTHONPATH = "/app/medical_booking"
DJANGO_SETTINGS_MODULE = "medical_booking.settings"
PYTHONUNBUFFERED = "1"
