[phases.setup]
nixPkgs = ['python312', 'gcc', 'python312Packages.virtualenv', 'mysql80', 'libmysqlclient']
aptPkgs = [
    'python3-pip',
    'python3-dev',
    'build-essential',
    'default-libmysqlclient-dev',
    'pkg-config',
    'libmysqlclient-dev'
]

[phases.install]
cmds = [
    'apt-get update',
    'apt-get install -y default-libmysqlclient-dev pkg-config',
    'python3 -m venv /app/venv',
    'source /app/venv/bin/activate',
    '/app/venv/bin/pip install --upgrade pip setuptools wheel',
    'cd medical_booking && LDFLAGS="-L/usr/lib/x86_64-linux-gnu" CPPFLAGS="-I/usr/include/mysql" /app/venv/bin/pip install -r requirements.txt --no-cache-dir'
]

[start]
cmd = 'source /app/venv/bin/activate && cd medical_booking && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn medical_booking.wsgi --bind 0.0.0.0:$PORT'

[env]
PYTHONPATH = "/app/medical_booking"
DJANGO_SETTINGS_MODULE = "medical_booking.settings"
PYTHONUNBUFFERED = "1"
PORT = "8000"
VIRTUAL_ENV = "/app/venv"
PATH = "/app/venv/bin:${PATH}"
